### ISSUE TITLE
Update jsbeautify to latest version

### ISSUE THREAD

**Issue by martinib77** [drewhamlett/brackets-beautify#127]
Jsbeautify 1.5.2 and up, solved a problem with angular templates:
https://github.com/beautify-web/js-beautify/issues/385%22%3E
Is it possible to update the library reference used by brackets-beautify?
Thanks

**Comment by naugtur** [comment]
+1

There are some differences in results of beautify used here and latest js-beautify when used with the same settings

**Comment by drewhamlett** [comment]
Hey guys this is fixed in the latest version.  It's int he registry.  Thanks!
