### ISSUE TITLE
Beautify on Save not working with the latest version of Brackets

### ISSUE THREAD

**Issue by tciuro** [drewhamlett/brackets-beautify#134]
I just installed Brackets Release 1.1 build 1.1.0-15558 (release ea908cae5). Beautify on Save doesn't seem to be working. Selecting the option manually works fine, but not on save. Is this a  Beautify issue or a Brackets one?

**Comment by egosapien** [comment]
I've got a suggested fix for this in the following pull request.
#130 
```
function onSave(event, doc) {
        var currentTimestamp = Date.now();

        if ((currentTimestamp - localStorage.getItem(COMMAND_TIMESTAMP)) > 1000) {
            format(true);
            localStorage.setItem(COMMAND_TIMESTAMP, currentTimestamp);
            CommandManager.execute(Commands.FILE_SAVE, {
                doc: doc
            });
        }
}
```

**Comment by drewhamlett** [comment]
Hey guys thanks for the help on this.  I've updated the registry with the commit.  Thanks @egosapien, @castlefields and @NexZhu  for the code
