### ISSUE TITLE
Expected '}' at column 3, not column 5 (on line 4). After setting to use "spaces, 2"

### ISSUE THREAD

**Issue by iegik** [drewhamlett/brackets-beautify#147]
After I customize Brackets to use 2 "spaces" instead 4 "spaces" - I got `Expected '}' at column 3, not column 5` errors on following code:
```
var arr = [
  {
    prop: 'value1'
    },
  {
    prop: 'value2'
    }
]
```

**Comment by T3charmy** [comment]
This is correct. at least for the code you supplied, you have your } at column 5, when it should be at 3 when you use 2 spaces( space space } )

**Comment by ahmedelsaka862** [comment]
You should write the code in this way ..

var arr = [{
    prop: 'value1'
}, {
    prop: 'value2'
}];
