### ISSUE TITLE
не работает "Beautify"

### ISSUE THREAD

**Issue by IDrakon** [drewhamlett/brackets-beautify#153]
sprint 3 build 1.3.0-16022 (release cd0a6aae5) 
Вот так выглядит js код:
https://drive.google.com/open?id=0B79v8XZ-aTqwWnVEZVVHdW1zcUU&authuser=0

После нажатия "Beautify" ничего не происходит.

**Comment by RoryPicko** [comment]
you only have the last bracket highlights, so only this will be beautified. You need to select all of the code first.
---- google translate
у вас есть только последние кронштейна моменты, так что только это будет благоустроена. Вы должны выбрать весь код в первую очередь.

**Comment by IDrakon** [comment]
Действительно, brackets при клике правой кнопкой мыши, выделяет строку в которой кликнули... Неудобно, но это уже проблема не в плагине.
