### ISSUE TITLE
Update js-beautify

### ISSUE THREAD

**Issue by RangerMauve** [drewhamlett/brackets-beautify#162]
JSX support has been added as well as some bug fixes, and not having that makes developing in Brackets not so fun.

**Comment by bitwiseman** [comment]
1.5.7 is out.
https://github.com/beautify-web/js-beautify/blob/master/CHANGELOG.md#v157

**Comment by drewhamlett** [comment]
I have updated to jsbeautify 1.5.10. So sorry for delay

**Comment by RangerMauve** [comment]
Awesome, thanks!
