### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by Hirse** [drewhamlett/brackets-beautify#171]
Hi Drew,

I would be interested to help maintain this project.
I had already created a [fork](https://github.com/Hirse/brackets-beautify) some time ago to apply some updates of the library and from PRs,
but I would be happy to merge that back into the original.

Best Regards,
Jan

**Comment by ApfelUser** [comment]
:+1:

**Comment by mak1e** [comment]
Hi @drewhamlett , I am also interested to help, I can assist in maintaining and work with @Hirse . 

How is this coming along? Any updates would be appreciated?

Thanks,
Mark

**Comment by Hirse** [comment]
@mak1e, feel free to help out on my fork.

**Comment by drewhamlett** [comment]
Hey Hirse I added you and @mak1e as contributors on this project yesterday.  Thanks for stepping up.   Would you want me to transfer to you or put under organization?  Thanks!

**Comment by Hirse** [comment]
Thanks @drewhamlett. 
I am happy to have the opportunity to help out for this great extension.
I don't mind either way about the transfer, but if you would like to do a transfer I guess an organization would be fairer

**Comment by drewhamlett** [comment]
Hey @Hirse thanks again.  I have transfered to a new organization and invited you as an owner.  Let me know if you have the invite.  Thanks

**Comment by Hirse** [comment]
Yes, got it. Thanks
