### ISSUE TITLE
Extension error

### ISSUE THREAD

**Issue by ZippoLag** [drewhamlett/brackets-beautify#93]
Hi, I'm getting an "Extension error (remove)" message on Beautify since Bracket's sprint 40. I've tried deleting the plugin, reloading, downloading from GitHub to no avail. Other plugins work just fine.

Sometimes the plugin works just fine when installing it, but then it won't work the next time I boot up the application.

Any clues as to what may be happening?

Are there any log files I can provide or inspect to try and debug this error?

Thanks.

**Comment by mayaa6** [comment]
It woks. Thanks @jazzmac93

**Comment by ajlatour** [comment]
@jazzmac93, your solution worked beautifully. Thanks

**Comment by davidbarredo** [comment]
Thanks a lot @jazzmac93 it worked ;-)

**Comment by drewhamlett** [comment]
Hi all, if you get the zip from this repo then you'll have to fetch the js-beautify code manually (thirdparty/jsbeautify).  I'd recommend cloning this repo using the Github app into the extensions directory(extensions/user).  This will resolve git submodules automatically.  Let me know if this is still an issue.

**Comment by SamOxigen** [comment]
same problem. And where is that @jazzmac93 solution, I can't find it to try?

**Comment by Hirse** [comment]
@SamOxigen I think it is @jazeelkt's comment (he might have changed his name).

Secondly, this issue is over three years old, from a time before Brackets 1.0, I am pretty sure you are experiencing a different issue (perhaps with similar symptoms).   
Please open a new issue and describe your problem in detail, including Dev Tools log if available.

**Comment by SamOxigen** [comment]
![image](https://user-images.githubusercontent.com/30326305/30667638-123a018c-9e0d-11e7-903e-130bb1323535.png)

This is my brackets' version info:
Release 1.10 build 1.10.0-17483 (release 024bee940) 
build timestamp: Wed Jul 05 2017 07:39:31 GMT+0100

I'm getting this message: "Installation failed. The extension encountered an error while starting up."

No update is prompting and, I searched for mentioned js files and couldn't find in the zip file I downloaded from github...

Thanks

**Comment by Hirse** [comment]
Please open a new issue as your problem is unrelated to the one discussed here and I don't like spamming all previous participants.
I will delete further unrelated comments.
